version: '3'
services:
  app:
    container_name: wraporg
    restart: always
    build: .
    ports:
      - '80:3000'
    depends_on:
      - mongodb
    links:
      - mongodb
  mongodb:
    container_name: mongodb
    image: mongo:4.2.0
    ports:
      - '27017:27017'